version: "3.8"

services:
  web-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development